"""Trader-Jev core domain and execution boundaries."""

from trader_jev.clock import LiveClock, ReplayClock, SystemClock
from trader_jev.decision import (
    DecisionCadenceConfig,
    JevAdapterConfig,
    JevDecision,
    JevDecisionAdapter,
    JevDecisionModel,
    JevRequest,
    RuleDecisionModel,
    SingleFlightDecisionRunner,
)
from trader_jev.execution import ExecutionConfig, PaperBroker, PaperExecutionConfig
from trader_jev.models import (
    Action,
    BarEvent,
    CapitalPolicy,
    DecisionSnapshot,
    EntryModel,
    FillEvent,
    InstrumentMetadata,
    NewsEvent,
    OrderBookEvent,
    OrderEvent,
    OrderIntent,
    PredictionOutput,
    QuoteEvent,
    ReplayEvent,
    RiskDecision,
    RiskProfile,
    TradeEvent,
    TradeIntent,
)
from trader_jev.portfolio import (
    FixedTimeExitPolicy,
    HybridExitPolicy,
    PaperPortfolioPolicy,
    PortfolioLedger,
    PortfolioPolicyConfig,
)
from trader_jev.replay import (
    PointInTimeViolation,
    ReplayConfig,
    ReplayEngine,
    ReplayError,
    ReplayMarketDataAdapter,
    ReplaySubscription,
    available_news,
    event_available_at,
    merge_replay_events,
    validate_event_point_in_time,
    validate_prediction_metadata,
)

__all__ = [
    "Action",
    "BarEvent",
    "CapitalPolicy",
    "DecisionCadenceConfig",
    "DecisionSnapshot",
    "EntryModel",
    "ExecutionConfig",
    "FillEvent",
    "InstrumentMetadata",
    "JevAdapterConfig",
    "JevDecision",
    "JevDecisionAdapter",
    "JevDecisionModel",
    "JevRequest",
    "NewsEvent",
    "OrderBookEvent",
    "OrderEvent",
    "OrderIntent",
    "PaperBroker",
    "PaperExecutionConfig",
    "PaperPortfolioPolicy",
    "PortfolioLedger",
    "PortfolioPolicyConfig",
    "PredictionOutput",
    "QuoteEvent",
    "RiskDecision",
    "RiskProfile",
    "RuleDecisionModel",
    "SingleFlightDecisionRunner",
    "TradeEvent",
    "TradeIntent",
    "FixedTimeExitPolicy",
    "HybridExitPolicy",
    "LiveClock",
    "PointInTimeViolation",
    "ReplayError",
    "ReplayEvent",
    "ReplayClock",
    "ReplayConfig",
    "ReplayEngine",
    "ReplayMarketDataAdapter",
    "ReplaySubscription",
    "SystemClock",
    "available_news",
    "event_available_at",
    "merge_replay_events",
    "validate_event_point_in_time",
    "validate_prediction_metadata",
]

__version__ = "0.1.0"
