"""Public dashboard facade aliases.

The implementation lives in :mod:`trader_jev.observability` so non-UI callers
can use the same read model without depending on a web framework.
"""

from trader_jev.observability import (
    AuditTrailStore,
    DashboardAPI,
    DashboardMode,
    DashboardOverview,
    DashboardQuery,
    DashboardReadModel,
    DashboardService,
    EquityPoint,
    ExperimentReport,
    ExperimentReportStore,
    ForwardPaperProgress,
    HealthRegistry,
    HealthState,
    HealthStatus,
    InMemoryLogStore,
    LogQuery,
    OrderView,
    PerformanceMetrics,
    PortfolioMetadata,
    PortfolioRegistration,
    PortfolioView,
    PositionView,
    StructuredLogHandler,
    StructuredLogRecord,
    SystemHealth,
    TradeAuditTrail,
    TradeRecord,
)

__all__ = [
    "AuditTrailStore",
    "DashboardAPI",
    "DashboardMode",
    "DashboardOverview",
    "DashboardQuery",
    "DashboardReadModel",
    "DashboardService",
    "EquityPoint",
    "ExperimentReport",
    "ExperimentReportStore",
    "ForwardPaperProgress",
    "HealthRegistry",
    "HealthState",
    "HealthStatus",
    "InMemoryLogStore",
    "LogQuery",
    "OrderView",
    "PerformanceMetrics",
    "PortfolioMetadata",
    "PortfolioRegistration",
    "PortfolioView",
    "PositionView",
    "StructuredLogHandler",
    "StructuredLogRecord",
    "SystemHealth",
    "TradeAuditTrail",
    "TradeRecord",
]
